//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BChatDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCH003
    {
        public string COLUMN001 { get; set; }
        public string COLUMN002 { get; set; }
        public string COLUMN003 { get; set; }
        public string COLUMN004 { get; set; }
        public Nullable<System.DateTime> COLUMN005 { get; set; }
        public Nullable<short> COLUMN006 { get; set; }
    
        public virtual User BCH001 { get; set; }
        public virtual User BCH0011 { get; set; }
        public virtual BCH002 BCH002 { get; set; }
    }
}
