//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BChatDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCH002
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BCH002()
        {
            this.BCH003 = new HashSet<BCH003>();
        }
    
        public string COLUMN001 { get; set; }
        public string COLUMN002 { get; set; }
        public Nullable<System.DateTime> COLUMN003 { get; set; }
        public Nullable<short> COLUMN004 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BCH003> BCH003 { get; set; }
    }
}
